version: '3'
services:
  gatling:
    build:
      context: docker-compose
      dockerfile: Dockerfile
    command: >
      mvn gatling:test
      -Dgatling.simulationClass=jp.co.soramitsu.load.simulation.MaximumSearchSimulation
      -DtargetProtocol=
      -DtargetURL=
      -DtargetPath=peer-0/api
      -DremoteLogin=
      -DremotePass=
      -DconcurrentUsers=1
      -Dtimes=10000
      -DeachLevelLasting=15
      -DseparatedByRampsLasting=1
      -DstartingFrom=0
      -DdomainSetUpRampUp=5
      -DduringSetUp=120
      -DsetUpUsersOnEachDomain=10
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"